name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install HF Hub
        run: pip install huggingface_hub

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.CAMPUS_TOKEN }}
        run: |
          hf auth login --token "$HF_TOKEN"

          # Clone space into /tmp folder (not inside repo)
          git clone https://huggingface.co/spaces/RohXn/CampusView /tmp/space

          # Copy only necessary repo files into space
          rsync -av --exclude='.git' ./ /tmp/space/

          # Commit & push
          cd /tmp/space
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto deploy" || echo "No changes to commit"
          git push
