name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.CAMPUS_TOKEN }}
        run: |
          pip install huggingface_hub
          hf auth login --token "$HF_TOKEN"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.CAMPUS_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git clone https://huggingface.co/spaces/RohXn/CampusView space_repo
          rsync -av --exclude ".git" ./ space_repo/
          cd space_repo
          git add .
          git commit -m "Auto deploy from GitHub Actions" || echo "No changes to commit"
          git push
